FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git
ENV CGO_ENABLED=0 GOBIN=/out
RUN go install -v github.com/minio/minio@RELEASE.2025-10-15T17-29-55Z

FROM alpine:3.22

RUN apk add --no-cache ca-certificates wget
COPY --from=builder /out/minio /usr/local/bin/minio

EXPOSE 9000 9001

ENTRYPOINT ["minio"]
