FROM node:25.6.0-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl \
    ffmpeg=7:5.1.9-0+deb12u1 \
    procps \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

RUN mkdir -p node_modules && chown node:node node_modules

USER node

CMD ["tail", "-f", "/dev/null"]
